-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
    -   id: end-of-file-fixer
