name: Build distribution files
on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: install dependencies
        run: yarn

      - name: build
        run: yarn build:dist

      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@5
        with:
          commit_message: Build distribution files
          branch: ${{ github.ref }}
