name: "minify"
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install dependencies
        run: npm install terser -g

      - name: build
        run: |
          terser dist/rpg_core.js --compress ecma=2018,drop_console=true,keep_classnames=true,keep_fnames=true,keep_infinity=true,passes=2,reduce_funcs=false,unsafe_math=true,unsafe_methods=true,unsafe_proto=true,unused=false --format ecma=2018,semicolons=false,wrap_iife=true --output dist/rpg_core.min.js
          terser dist/rpg_managers.js --compress ecma=2018,drop_console=true,keep_classnames=true,keep_fnames=true,keep_infinity=true,passes=2,reduce_funcs=false,unsafe_math=true,unsafe_methods=true,unsafe_proto=true,unused=false --format ecma=2018,semicolons=false,wrap_iife=true --output dist/rpg_managers.min.js
          terser dist/
rpg_objects.js --compress ecma=2018,drop_console=true,keep_classnames=true,keep_fnames=true,keep_infinity=true,passes=2,reduce_funcs=false,unsafe_math=true,unsafe_methods=true,unsafe_proto=true,unused=false --format ecma=2018,semicolons=false,wrap_iife=true --output dist/
rpg_objects.min.js
          terser dist/
rpg_scenes.js --compress ecma=2018,drop_console=true,keep_classnames=true,keep_fnames=true,keep_infinity=true,passes=2,reduce_funcs=false,unsafe_math=true,unsafe_methods=true,unsafe_proto=true,unused=false --format ecma=2018,semicolons=false,wrap_iife=true --output dist/
rpg_scenes.min.js
          terser dist/rpg_sprites.js --compress ecma=2018,drop_console=true,keep_classnames=true,keep_fnames=true,keep_infinity=true,passes=2,reduce_funcs=false,unsafe_math=true,unsafe_methods=true,unsafe_proto=true,unused=false --format ecma=2018,semicolons=false,wrap_iife=true --output dist/rpg_sprites.min.js
          terser dist/rpg_windows.js --compress ecma=2018,drop_console=true,keep_classnames=true,keep_fnames=true,keep_infinity=true,passes=2,reduce_funcs=false,unsafe_math=true,unsafe_methods=true,unsafe_proto=true,unused=false --format ecma=2018,semicolons=false,wrap_iife=true --output dist/rpg_windows.min.js

      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Minify source code
          branch: ${{ github.ref }}

