name: Continuous Integration

permissions:
  pull-requests: read
  contents: write

# This action works with pull requests
on:
  pull_request:
    branches:
      - master
      - experimental

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,json,md}
